### ISSUE TITLE
Class FFMpeg could not be found

### ISSUE THREAD

**Issue by tammyruihuang** [PHP-FFMpeg/PHP-FFMpeg#417] opened 2017-10-02 17:30 UTC
I tried to use your code in my case. Here's the error message I received after I run the code shown below: Fatal error: Uncaught Error: Class 'ffmpeg\src\FFMpeg\FFMpeg\FFMpeg' not found in ...

```
<?php 
# this autoload is added by Google Cloud API since I am using its speech engine as well.
require __DIR__ . '/vendor/autoload.php';

use ffmpeg\src\FFMpeg\FFMpeg;

$fileName = __DIR__ . '/audiofiles/trimmedClip.wav';

$ffmpeg = FFMpeg\FFMpeg::create();
$audio = $ffmpeg->open($filename);

$format = new FFMpeg\Format\Audio\Flac();
$format->on('progress', function($audio, $format, $percentage) {
   echo "$percentage % transcoded"; 
});

$format
    ->setAudioChannels(2)
    ->setAudioKiloBitrate(256);

$audio->save($format, 'trimmedClip.flac');

return true;
?>

```

**Comment by jens1o** [comment] 2017-10-02 17:34
Please do not create multiple issues for one topic. Duplicate of https://github.com/PHP-FFMpeg/PHP-FFMpeg/issues/416

**Closed by jens1o** 2017-10-02 17:34 UTC

**Comment by tammyruihuang** [comment] 2017-10-02 17:35
I am sorry but the issue was not solved. There’s no way I can use the code right now.
