### ISSUE TITLE
Converting WMV / AVI's to X264 for HTML5 player.

### ISSUE THREAD

**Issue by CameronCT** [PHP-FFMpeg/PHP-FFMpeg#544] opened 2018-06-26 09:25 UTC
| Q              | A
| -------------- | ---
| Bug?           | maybe
| New Feature?   | no
| Version Used   | Latest
| FFmpeg Version | FFmpeg 2.8.14
| OS             | Ubuntu 16.04

So the code I am testing with is the same as the "standard" usage as described in the `README.MD` file. My issue is that I'm trying to transcode a WMV & AVI file to X264 but it will not play properly on an HTML5 Video player. It plays fine on my computer and any type of media player, but for some reason not on the HTML5 video player. I've read and heard it has something to do with this `yuv420p` flag, but no idea how to manually add it in PHP-FFMPEG or if there's something that fixes it.

```
$ffmpeg = FFMpeg\FFMpeg::create(array(
            'ffmpeg.binaries'  => '/usr/bin/ffmpeg',
            'ffprobe.binaries' => '/usr/bin/ffprobe',
            'timeout'          => 9000, // The timeout for the underlying process
            'ffmpeg.threads'   => 1,   // The number of threads that FFMpeg should use
        ));
        $video = $ffmpeg->open('/path/to/file');

        $format = new FFMpeg\Format\Video\X264('libmp3lame', 'libx264');
        $format
            ->setKiloBitrate(2500);
        $video
            ->save($format, '/path/to/mp4');
```

**Comment by jens1o** [comment] 2018-06-26 16:02
Could you please send us the file you are encoding and the file that turns out? Unfortunately, I only have a *very* limited set of videos I can test with :)

**Comment by CameronCT** [comment] 2018-06-26 20:05
https://www.dropbox.com/s/euc5p0nfxlisswb/Files.zip?dl=0

The files you are looking for are above, I have both before & afters of the AVI / WMV's since it only occurs for both.

**Comment by CameronCT** [comment] 2018-07-01 03:20
Hey, any update on this by chance?

**Comment by jens1o** [comment] 2018-07-01 08:54
I cut the video to 10 seconds, to make it's encoding process faster, but I'm still not able to reproduce this.

> HTML5 video player.

I dragged the wmv-file into Firefox and it's playing perfectly fine.
[test.zip](https://github.com/PHP-FFMpeg/PHP-FFMpeg/files/2152660/test.zip)

**Comment by CameronCT** [comment] 2018-07-03 00:13
Hmm, is it something with my FFMPEG settings? Does everything that I have look correct to you?

**Comment by jens1o** [comment] 2018-07-03 12:23
Yeah, I also think this is system specific :/

**Comment by CameronCT** [comment] 2018-07-03 20:55
Last time I made a transcoding system was on CentOS though that was a year now since I've done it. Which is why my site hasn't been allowing anything that's not MP4's.

**Comment by jens1o** [comment] 2018-07-04 14:17
This wrapper does not handle this at all. :/ It only provides a seamless interface for interacting with it nicely.

**Comment by jens1o** [comment] 2018-07-14 06:01
Thank you Sir, and that's a good suggestion to close the issue. And yes, it is really broad.

**Closed by jens1o** 2018-07-14 06:01 UTC
Labels: need more info
