### ISSUE TITLE
Not installed

### ISSUE THREAD

**Issue by averichev** [PHP-FFMpeg/PHP-FFMpeg#478] opened 2018-02-02 11:55 UTC
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | v0.11.0
| FFmpeg Version | ffmpeg version 2.2.1
| OS             | CentOS release 6.9 (Final)

#### Actual Behavior

not installed

#### Expected Behavior

Must be installed

#### Steps to Reproduce

1. Install symfony 4 
```
composer create-project symfony/skeleton my_project
```
2. I'm trying to install a library

```
composer require php-ffmpeg/php-ffmpeg
```
And i have error (see screenshot)
![image](https://user-images.githubusercontent.com/5820708/35732047-0ed376f0-0829-11e8-88f6-91e86c6dcc75.png)

#### Possible Solutions

Change requirements

**Comment by averichev** [comment] 2018-02-02 11:56
Help please

**Comment by jens1o** [comment] 2018-02-02 12:52
duplicate of #470 

Please do not use words like `help`. Thank you. Oh, and search for duplicates, too.

**Closed by jens1o** 2018-02-02 12:52 UTC
