### ISSUE TITLE
Add 'copy' to available codecs

### ISSUE THREAD

**Issue by nathanmal** [PHP-FFMpeg/PHP-FFMpeg#690] opened 2019-12-05 02:30 UTC
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | Yes
| Version Used   | Specific tag or commit sha
| FFmpeg Version | FFmpeg or AVConv and version
| OS             | Your OS and version

Is it possible to add 'copy' as an available video/audio codec for X264?

I've tested this by simply adding it to the front of each array in FFMpeg\Format\Video\X264 and seems to work fine

This is helpful when you have a video of the same codec/size etc and you don't care about converting bitrate, you just want to add +faststart, for example, as it doesn't have to re-encode the entire video and completes in only a few seconds. 

any reason not to allow this as an option?

**Comment by jens1o** [comment] 2020-03-23 09:54
Duplicate of #645. The version was just released a few moments ago.

**Closed** 2020-03-23 09:55 UTC
