### ISSUE TITLE
I have an audio file ,But the open method in FFMpeg \ FFMpeg will be considered a video file

### ISSUE THREAD

**Issue by szliugx** [PHP-FFMpeg/PHP-FFMpeg#402] opened 2017-08-30 05:14 UTC
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | "php-ffmpeg/php-ffmpeg": "^0.9.5",
| FFmpeg Version |ffmpeg version N-86950-g1bef008 Copyright (c) 2000-2017 the FFmpeg developers
| OS             | win7 64 and centos5.7

#### Actual Behavior

I have an audio file
But the open method in FFMpeg \ FFMpeg will be considered a video file
I print out $ streams and $streams-> videos () and $streams-> audios () in the open method.
$Streams as follows:
```
object(FFMpeg\FFProbe\DataMapping\StreamCollection)#93 (1) {
  ["streams":"FFMpeg\FFProbe\DataMapping\StreamCollection":private]=>
  array(2) {
    [0]=>
    object(FFMpeg\FFProbe\DataMapping\Stream)#104 (1) {
      ["properties":"FFMpeg\FFProbe\DataMapping\AbstractData":private]=>
      array(21) {
        ["index"]=>
        int(0)
        ["codec_name"]=>
        string(3) "mp3"
        ["codec_long_name"]=>
        string(24) "MP3 (MPEG audio layer 3)"
        ["codec_type"]=>
        string(5) "audio"
        ["codec_time_base"]=>
        string(7) "1/44100"
        ["codec_tag_string"]=>
        string(12) "[0][0][0][0]"
        ["codec_tag"]=>
        string(6) "0x0000"
        ["sample_fmt"]=>
        string(4) "s16p"
        ["sample_rate"]=>
        string(5) "44100"
        ["channels"]=>
        int(2)
        ["channel_layout"]=>
        string(6) "stereo"
        ["bits_per_sample"]=>
        int(0)
        ["r_frame_rate"]=>
        string(3) "0/0"
        ["avg_frame_rate"]=>
        string(3) "0/0"
        ["time_base"]=>
        string(10) "1/14112000"
        ["start_pts"]=>
        int(353600)
        ["start_time"]=>
        string(8) "0.025057"
        ["duration_ts"]=>
        float(3388170240)
        ["duration"]=>
        string(10) "240.091429"
        ["bit_rate"]=>
        string(6) "320000"
        ["disposition"]=>
        array(12) {
          ["default"]=>
          int(0)
          ["dub"]=>
          int(0)
          ["original"]=>
          int(0)
          ["comment"]=>
          int(0)
          ["lyrics"]=>
          int(0)
          ["karaoke"]=>
          int(0)
          ["forced"]=>
          int(0)
          ["hearing_impaired"]=>
          int(0)
          ["visual_impaired"]=>
          int(0)
          ["clean_effects"]=>
          int(0)
          ["attached_pic"]=>
          int(0)
          ["timed_thumbnails"]=>
          int(0)
        }
      }
    }
    [1]=>
    object(FFMpeg\FFProbe\DataMapping\Stream)#105 (1) {
      ["properties":"FFMpeg\FFProbe\DataMapping\AbstractData":private]=>
      array(30) {
        ["index"]=>
        int(1)
        ["codec_name"]=>
        string(5) "mjpeg"
        ["codec_long_name"]=>
        string(11) "Motion JPEG"
        ["codec_type"]=>
        string(5) "video"
        ["codec_time_base"]=>
        string(3) "0/1"
        ["codec_tag_string"]=>
        string(12) "[0][0][0][0]"
        ["codec_tag"]=>
        string(6) "0x0000"
        ["width"]=>
        int(640)
        ["height"]=>
        int(640)
        ["coded_width"]=>
        int(640)
        ["coded_height"]=>
        int(640)
        ["has_b_frames"]=>
        int(0)
        ["sample_aspect_ratio"]=>
        string(3) "1:1"
        ["display_aspect_ratio"]=>
        string(3) "1:1"
        ["pix_fmt"]=>
        string(8) "yuvj444p"
        ["level"]=>
        int(-99)
        ["color_range"]=>
        string(2) "pc"
        ["color_space"]=>
        string(7) "bt470bg"
        ["chroma_location"]=>
        string(6) "center"
        ["refs"]=>
        int(1)
        ["r_frame_rate"]=>
        string(7) "90000/1"
        ["avg_frame_rate"]=>
        string(3) "0/0"
        ["time_base"]=>
        string(7) "1/90000"
        ["start_pts"]=>
        int(2255)
        ["start_time"]=>
        string(8) "0.025056"
        ["duration_ts"]=>
        int(21608229)
        ["duration"]=>
        string(10) "240.091433"
        ["bits_per_raw_sample"]=>
        string(1) "8"
        ["disposition"]=>
        array(12) {
          ["default"]=>
          int(0)
          ["dub"]=>
          int(0)
          ["original"]=>
          int(0)
          ["comment"]=>
          int(0)
          ["lyrics"]=>
          int(0)
          ["karaoke"]=>
          int(0)
          ["forced"]=>
          int(0)
          ["hearing_impaired"]=>
          int(0)
          ["visual_impaired"]=>
          int(0)
          ["clean_effects"]=>
          int(0)
          ["attached_pic"]=>
          int(1)
          ["timed_thumbnails"]=>
          int(0)
        }
        ["tags"]=>
        array(1) {
          ["comment"]=>
          string(29) "Media (e.g. label side of CD)"
        }
      }
    }
  }
}

```

#### Expected Behavior
For example: .MP3 file is audio, .mp4 file is video

#### Steps to Reproduce
Occurs when the audio is intercepted：
Argument 2 passed to FFMpeg\Filters\Video\ClipFilter::apply() must be an instance of FFMpeg\Format\VideoInterface, instance of FFMpeg\Format\Audio\Mp3 given, called in /data/www/daoyan_0.2.1/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Media/Video.php on line 84 and defined

#### Possible Solutions

Codec_type are audio and video, whether the media file does not change the case, according to some media files to distinguish the suffix name of this file is audio or video

**Comment by jens1o** [comment] 2017-08-30 08:13
The video you have looks to be the audio cover. Does the audio file has one?

**Comment by szliugx** [comment] 2017-08-30 11:50
This is the test audio address I encountered this problem:
```
https://github.com/szliugx/test/blob/master/CRITTY%20-%20遇萤（纯歌版）.mp3
```

**Comment by szliugx** [comment] 2017-08-30 13:10
This may be my media file MetaData things too much
I cleared the MetaData by this method and passed it
```
    /**
     * removeMetadata
     * @param $audioFile
     * @param $outFile
     * @return bool
     */
    public static function removeMetadata($audioFile, $outFile)
    {
        try{
            $audio = self::getInstance()->open($audioFile);
            $audio->filters()->addMetadata();
            $audio->save(self::$audio_format, $outFile);

            return true;
        }catch (Exception $e){

            return false;
        }
    }
```
Because I put this document in the win7 window related operations will throw exception, the following is my window in the operation of the picture:
![Exception picture](https://github.com/szliugx/test/blob/master/audio_file.png)

**Comment by jens1o** [comment] 2017-08-31 09:26
Can you give me the file after removing the metadata? I'm sure it will not remove the cover itself...

**Comment by phylaxis** [comment] 2017-12-29 00:15
I'm having the exact same issue with an MP3 file I'm trying to work with. I think part of the problem might be this file is an MP3 with Chapter support. Is there a way to "force" FFMPEG to only open and work with the audio portion?

**Comment by jens1o** [comment] 2017-12-30 19:42
I'm not aware how you can tell the lib to do so. 

first of all, I need to get something so I can reproduce it.

**Comment by pieterdt** [comment] 2019-02-15 21:17
having the same issue, I can provide you the file if you want.

In my case, I'm dealing with a lot of mp3 files for which i want to create a sample clip of a couple of seconds.

If the file is detected (after $ffmpeg->open(...)) as Audio, the clipping works.
When the file is detected as video, the clipping complains that it expects to get a Video, but received an Audio file. It indeed gets an audio file, but it initially detects it wrongly as a video file hence loads the wrong processors.

The difference I see with ffprobe on the command line between a file that gets correctly detected and one that gets wrongly detected:
detected as video:
`Duration: 00:00:40.41, start: 0.025056, bitrate: 452 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, s16p, 298 kb/s
    Metadata:
      encoder         : LAME3.100
    Stream #0:1: Video: png, rgb24(pc), 600x600 [SAR 11810:11810 DAR 1:1], 90k tbr, 90k tbn, 90k tbc
    Metadata:
      comment         : Cover (front)`
different file, created with another software, detected correctly as audio file:
`Duration: 00:01:25.61, start: 0.000000, bitrate: 320 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, s16p, 320 kb/s`

It looks like the album cover is added as a very short video stream.
Now the weird thing to me is that $ffmpeg->open decides on a wrong type, while the filter detects the correct type.

In the problematic case, the following code returns 'FFMpeg\Media\Video':
`$ffmpeg = FFMpeg::create();
$song = $ffmpeg->open($uri_remote);
echo get_class($song);`

and if I try to create the sample with the following code:
`$song->filters()->clip(TimeCode::fromSeconds($sampleStart),TimeCode::fromSeconds($sampleDuration));`

complains with the following message:
`TypeError: Argument 2 passed to FFMpeg\Filters\Video\ClipFilter::apply() must be an instance of FFMpeg\Format\VideoInterface, instance of FFMpeg\Format\Audio\Mp3`

**Comment by jens1o** [comment] 2019-02-15 21:26
Could you pass me the file, please? For example by e-mailing it to me. :)

**Comment by pieterdt** [comment] 2019-02-15 21:28
sure, what address can i send it to? This one? Or will that be a message on
github?

Pieter

**Comment by jens1o** [comment] 2019-02-16 08:20
I can reproduce it with the file you sent and the following script:

```
<?php
declare(strict_types=1);

require_once './../vendor/autoload.php';

use FFMpeg\FFMpeg;
use FFMpeg\Media\{Video, Audio};

$ffmpeg = FFMpeg::create();

$mediaFile = $ffmpeg->open('sample.mp3');

if ($mediaFile instanceof Video) {
    echo "Hit!";
}
```

**Comment by jens1o** [comment] 2019-02-16 08:31
I think I know why this happens. 

FFProbe gives the following reply when I ask what streams the audio you provided gave.

```json
[
  {
    "index": 0,
    "codec_name": "mp3",
    "codec_long_name": "MP3 (MPEG audio layer 3)",
    "codec_type": "audio",
    "codec_time_base": "1/44100",
    "codec_tag_string": "[0][0][0][0]",
    "codec_tag": "0x0000",
    "sample_fmt": "fltp",
    "sample_rate": "44100",
    "channels": 2,
    "channel_layout": "stereo",
    "bits_per_sample": 0,
    "r_frame_rate": "0/0",
    "avg_frame_rate": "0/0",
    "time_base": "1/14112000",
    "start_pts": 353600,
    "start_time": "0.025057",
    "duration_ts": 570286080,
    "duration": "40.411429",
    "bit_rate": "298356",
    "disposition": {
      "default": 0,
      "dub": 0,
      "original": 0,
      "comment": 0,
      "lyrics": 0,
      "karaoke": 0,
      "forced": 0,
      "hearing_impaired": 0,
      "visual_impaired": 0,
      "clean_effects": 0,
      "attached_pic": 0,
      "timed_thumbnails": 0
    },
    "tags": {
      "encoder": "LAME3.100"
    }
  },
  {
    "index": 1,
    "codec_name": "png",
    "codec_long_name": "PNG (Portable Network Graphics) image",
    "codec_type": "video",
    "codec_time_base": "0/1",
    "codec_tag_string": "[0][0][0][0]",
    "codec_tag": "0x0000",
    "width": 600,
    "height": 600,
    "coded_width": 600,
    "coded_height": 600,
    "has_b_frames": 0,
    "sample_aspect_ratio": "1:1",
    "display_aspect_ratio": "1:1",
    "pix_fmt": "rgb24",
    "level": -99,
    "color_range": "pc",
    "refs": 1,
    "r_frame_rate": "90000/1",
    "avg_frame_rate": "0/0",
    "time_base": "1/90000",
    "start_pts": 2255,
    "start_time": "0.025056",
    "duration_ts": 3637029,
    "duration": "40.411433",
    "disposition": {
      "default": 0,
      "dub": 0,
      "original": 0,
      "comment": 0,
      "lyrics": 0,
      "karaoke": 0,
      "forced": 0,
      "hearing_impaired": 0,
      "visual_impaired": 0,
      "clean_effects": 0,
      "attached_pic": 1,
      "timed_thumbnails": 0
    },
    "tags": {
      "comment": "Cover (front)"
    }
  }
]
```
(Note that the audio cover gets mapped as an video!)

**Comment by jens1o** [comment] 2019-02-16 09:00
Honestly, I'm not sure how to fix this problem without involving breaking changes. 

The fix for this behavior is as simple as applying this diff:

```diff
diff --git a/src/FFMpeg/FFMpeg.php b/src/FFMpeg/FFMpeg.php
index 91ce361..f5dfa58 100644
--- a/src/FFMpeg/FFMpeg.php
+++ b/src/FFMpeg/FFMpeg.php
@@ -93,7 +93,11 @@ class FFMpeg
             throw new RuntimeException(sprintf('Unable to probe "%s".', $pathfile));
         }
 
-        if (0 < count($streams->videos())) {
+        $videoStreams = $streams->videos();
+
+        // do not detect audio artwork(encoded as a png) as a video stream
+        // workaround for not needed ffprobe feature
+        if (0 < count($videoStreams) && 'png' !== $videoStreams->all()[0]->get('codec_name')) {
             return new Video($pathfile, $this->driver, $this->ffprobe);
         } elseif (0 < count($streams->audios())) {
             return new Audio($pathfile, $this->driver, $this->ffprobe);

```

**Comment by pieterdt** [comment] 2019-02-17 20:40
great, thx, will apply it as such!

**Comment by jens1o** [comment] 2019-03-17 10:04
@pieterdt Did you found any regressions?<

**Comment by jens1o** [comment] 2019-03-17 10:08
duplicate https://github.com/PHP-FFMpeg/PHP-FFMpeg/issues/402

**Closed** 2019-03-17 10:08 UTC
Labels: bug, confirmed, duplicate

**Comment by lugreen09** [comment] 2019-11-18 22:31
@jens1o Thank you! For anyone still facing issues, I have tested the patch on multiple different files. I encountered some problems which I've fixed as far as I'm aware.

Issues: If an audio file didn't have a cover it would cause a "fatal error on ->get()", the audio files I tested returned a few different codec names. This code seems to fix these issues.

` public function open($pathfile)
    {
        if (null === $streams = $this->ffprobe->streams($pathfile)) {
            throw new RuntimeException(sprintf('Unable to probe "%s".', $pathfile));
        }
		
		/*if (0 < count($streams->videos()) ) {*/
		
		$videoStreams		= $streams->videos();
		
		/*
		Do not detect audio artwork(encoded as a png) as a video stream
		workaround for not needed ffprobe feature
		*/
		
		if (0 < count($videoStreams) && !in_array((isset($videoStreams->all()[0]) ? $videoStreams->all()[0]->get('codec_name') : ''), ['png', 'jpeg', 'mjpeg']) /*'png' !== $videoStreams->all()[0]->get('codec_name')*/) {
            return new Video($pathfile, $this->driver, $this->ffprobe);
        } elseif (0 < count($streams->audios())) {
            return new Audio($pathfile, $this->driver, $this->ffprobe);
        }

        throw new InvalidArgumentException('Unable to detect file format, only audio and video supported');
    }`

**Comment by robphillips** [comment] 2023-10-16 19:31
Here's a workaround that doesn't involve patching or instantiating streamable media twice. Plus checks for JPEG. It might even be taken a step further by validating the extension against known mime types.

```php
$ffmpeg = FFMpeg::create();
$streams = $ffmpeg->getFFProbe()->streams('/path/to/file.mp3');

// Validate the codec types are actually video streams.
$videoStreams = $streams->videos()->count();
foreach ($streams->videos() as $stream) {
  if (in_array($stream->get('codec_name'), ['png', 'jpeg', 'mjpeg'])) {
    $videoStreams--;
  }
}

if ($videoStreams) {
  $stream = new Video($uri, $ffmpeg->getFFMpegDriver(), $ffmpeg->getFFProbe());
}
elseif ($streams->audios()->count()) {
  $stream = new Audio($uri, $ffmpeg->getFFMpegDriver(), $ffmpeg->getFFProbe());
}

// Do something with the abstract streamable media.
```

Would be nice if this is eventually fixed in the package itself. The patch in https://github.com/PHP-FFMpeg/PHP-FFMpeg/issues/402#issuecomment-464319454 is probably incomplete considering MP3 supports multiple cover art images in both PNG and JPEG formats.
