### ISSUE TITLE
Laravel 5.6安装PHP-FFMpeg报错

### ISSUE THREAD

**Issue by virtual163** [PHP-FFMpeg/PHP-FFMpeg#563] opened 2018-08-17 08:19 UTC
| Q              | A
| -------------- | ---
| Bug?           | 安装报错
| Version Used   | Laravel5.6
| FFmpeg Version | 3.4.2-2
| OS             | Ubuntu 18.04

#### Actual Behavior

laravel 5.6 安装php-ffmpeg
$sudo composer require "php-ffmpeg/php-ffmpeg"
[sudo] password for mrchen:
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Using version ^0.12.0 for php-ffmpeg/php-ffmpeg
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1

    Installation request for php-ffmpeg/php-ffmpeg ^0.12.0 -> satisfiable by php-ffmpeg/php-ffmpeg[v0.12].

    Conclusion: remove symfony/console v4.1.3
    php-ffmpeg/php-ffmpeg v0.12 requires alchemy/binary-driver ^1.5 -> satisfiable by alchemy/binary-driver[1.5.0, 1.6.0].
    alchemy/binary-driver 1.5.0 requires symfony/process ~2.0 -> satisfiable by symfony/process[2.0.4, 2.0.5, 2.0.6, 2.0.7,
    安装不上,这是不兼容还是,人有碰到过吗,应该怎样解决呢???
经过检查发现提composer里面的有些插件和laravel里抽的版本不兼容导致，经过修改后现在可以使用。

**Comment by jens1o** [comment] 2018-08-17 09:04
Duplicate of #470

**Closed by jens1o** 2018-08-17 09:04 UTC
