### ISSUE TITLE
Division by zero after updating to recent version

### ISSUE THREAD

**Issue by vrajroham** [PHP-FFMpeg/PHP-FFMpeg#347] opened 2017-04-10 13:47 UTC
| Q              | A
| -------------- | ---
| Bug?           | Yes
| New Feature?   | no
| Version Used   | 0.9.2
| FFmpeg Version | git-2017-01-22-f1214ad 
| OS             | Ubuntu 14

#### Actual Behavior

Previously I was using version `0.6.*` after updating to newer version getting following error 

 `exception 'ErrorException' with message 'Division by zero'` 

point to file

`....src/FFMpeg/Format/ProgressListener/AbstractProgressListener.php:178`

I am trying to convert `*.webm` to `*.mp4`. Also output files are being generated but exception occurs.

#### Expected Behavior

Exception should be handled so script should not break.

#### Steps to Reproduce

Below is my code

    $video = $ffmpeg->open(storage_path("app/".$this->pending->video_source)); //webm file
    $ffmpeg = FFMpeg::create([
                'ffmpeg.binaries' => '/opt/ffmpeg/bin/ffmpeg',
                'ffprobe.binaries' => '/opt/ffmpeg/bin/ffprobe',
                'timeout' => 9800, 
                'ffmpeg.threads' => 12
            ]);
    $format=new \FFMpeg\Format\Video\X264('libmp3lame', 'libx264');
    $format->setKiloBitrate(100);        
    $video->save($format,$mp4name); //$mp4name consist output location with file name

**Comment by jens1o** [comment] 2017-04-10 13:52
That's known. Duplicate of #333 will be fixed in #334 once @Romain 's back

**Comment by Romain** [comment] 2017-04-12 16:07
Thanks @jens1o.
I'll prepare a new version today to push this fix.

**Closed** 2017-04-12 16:11 UTC
