### ISSUE TITLE
php 7 laravel 5.6 install error

### ISSUE THREAD

**Issue by TechShankar** [PHP-FFMpeg/PHP-FFMpeg#504] opened 2018-03-27 13:47 UTC
this project works correctly in laravel 5.5. not working in laravel 5.6

please help how to fix this problem

$ composer require php-ffmpeg/php-ffmpeg
Using version ^0.11.1 for php-ffmpeg/php-ffmpeg
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install php-ffmpeg/php-ffmpeg v0.11.1-pl-1
    - Conclusion: remove evenement/evenement v3.0.1
    - Installation request for php-ffmpeg/php-ffmpeg ^0.11.1 -> satisfiable by php-ffmpeg/php-ffmpeg[v0.11.1, v0.11.1-pl-1].
    - Conclusion: don't install evenement/evenement v3.0.1
    - php-ffmpeg/php-ffmpeg v0.11.1 requires evenement/evenement ^2.0 || ^1.0 -> satisfiable by evenement/evenement[v1.0.0, v1.1.0, v2.0.0, v2.1.0].
    - Can only install one of: evenement/evenement[v1.0.0, v3.0.1].
    - Can only install one of: evenement/evenement[v1.1.0, v3.0.1].
    - Can only install one of: evenement/evenement[v2.0.0, v3.0.1].
    - Can only install one of: evenement/evenement[v2.1.0, v3.0.1].
    - Installation request for evenement/evenement (locked at v3.0.1) -> satisfiable by evenement/evenement[v3.0.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by jens1o** [comment] 2018-03-27 16:10
duplicate of #470

**Closed** 2018-03-27 16:11 UTC
Labels: duplicate
