### ISSUE TITLE
How to set a -crf quality?

### ISSUE THREAD

**Issue by Sensetivity** [PHP-FFMpeg/PHP-FFMpeg#486] opened 2018-02-22 15:12 UTC
How to set a -crf quality? I see just a kilobytes option.

**Comment by jens1o** [comment] 2018-02-22 17:19
duplicate of #418

**Closed by jens1o** 2018-02-22 17:19 UTC

**Comment by ContatKarc** [comment] 2019-02-12 15:24
How to use SimpleFilter?

**Comment by jens1o** [comment] 2019-02-13 13:12
@ContatKarc You can see https://github.com/PHP-FFMpeg/PHP-FFMpeg/blob/233742db0a0ec9b7e648b49b5725c36e16ca4e26/tests/Unit/Filters/FiltersCollectionTest.php#L42-L50

This is how it works.

**Comment by Abdelhady** [comment] 2019-04-09 17:47
I still don't understand how to use `SimpleFilter` to pass these parameters `-crf 27 -preset veryfast` ?!

**Comment by jens1o** [comment] 2019-04-10 17:09
Let `$audio` be an instance of `FFMpeg\Media\Audio`.

You can now put `$audio->addFilter($filter)` where `$filter` is an instance of `FFMpeg\Filters\Audio\SimpleFilter`. You basically give the array of parameters to the constructor of `SimpleFilter`.

Please take a revision on basic OOP concepts and their implementations in PHP.

**Comment by Abdelhady** [comment] 2019-04-11 10:44
REALLY! you are talking about OOP! REALLY! .. anyway..

The point is, there is no single example on using the `SimpleFilter` (even the one in the unit tests, it doesn't tell what cli parameters are used in the example) & how the passed parameters array is formed is not clear at all! (should they be written in a simple array, or an associative one..), so based on the example I've mentioned where I asked about adding these specific cli parameters `-crf 27 -preset veryfast`, will it be like this?

```php
$video->addFilter(new SimpleFilter(['-crf', '27', '-preset', 'veryfast']));
```

and btn, if your answer is 'yes', then you should have answered with this one-liner instead of that weird answer you wrote!
