### ISSUE TITLE
Unable to load FFProbe and Executable not found, proposed : avprobe, ffprobe

### ISSUE THREAD

**Issue by aminyazdanpanah** [PHP-FFMpeg/PHP-FFMpeg#409] opened 2017-09-11 12:59 UTC
Hi there,
I'm trying to run PHP-FFMpeg on a server and I get the following error:

`2/2`
`ExecutableNotFoundException in FFProbeDriver.php line 50:`
`Unable to load FFProbe`
`1/2`
`ExecutableNotFoundException in AbstractBinary.php line 160:`
`Executable not found, proposed : avprobe, ffprobe`

The result of these:

`var_dump(getenv('PATH'));`
`var_dump(exec('which ffmpeg'));`
`var_dump(ini_get('open_basedir'));`
`var_dump(is_file(exec('which ffmpeg')));`
`var_dump(is_executable(exec('which ffmpeg')));`

is here:

`string(29) "/sbin:/usr/sbin:/bin:/usr/bin"`
`string(15) "/usr/bin/ffmpeg"`
`string(74) "/home/video/:/tmp:/var/tmp:/usr/local/lib/php/:/usr/local/php56/lib/php/"`
`bool(false)`
`bool(false)`

So I don't have any idea why is not working?
any suggestions?

**Comment by jens1o** [comment] 2017-09-11 16:30
Duplicate of https://github.com/PHP-FFMpeg/PHP-FFMpeg/issues/172

So far I didn't found an solution. 😭

**Closed by jens1o** 2017-09-11 16:30 UTC
