### ISSUE TITLE
the converted audio file is larger than I expected

### ISSUE THREAD

**Issue by mohammad6006** [PHP-FFMpeg/PHP-FFMpeg#720] opened 2020-05-04 12:23 UTC
| Q              | A
| -------------- | ---
| Bug?           | no
| New Feature?   | no
| Version Used   | Specific tag or commit sha
| FFmpeg Version | 0.14
| OS             | ubuntu 16

#### Actual Behavior

the converted audio file is larger than I expected

for example : 

FLAC : 21 Mb
converted mp3 128 : 6 MB

#### Expected Behavior

I expect mp3 128 about 3 Mb 

for convert from FLAC to MP3 128
```
        $lowBitrateFormat = (new \FFMpeg\Format\Audio\Mp3)->setAudioKiloBitrate(128);
```
and export

```
            FFMpeg::fromDisk('audios_disk')->open($localpath)
            ->export()
            ->inFormat($lowBitrateFormat)
            ->save('test.mp3')
```
but converted audio file size is larger than expected
flac : 21 Mb

mp3 128: 6 Mb ( should be 3 Mb)

**Comment by jens1o** [comment] 2020-05-09 06:07
duplicate of #430

**Closed by jens1o** 2020-05-09 06:07 UTC
