### ISSUE TITLE
Merge two or more video files

### ISSUE THREAD

**Issue by clagiordano** [PHP-FFMpeg/PHP-FFMpeg#188] opened 2015-11-27 16:46 UTC
Hi,

there is a way to merge (concatenate) two or more video files?

Best regards.

**Comment by patkar** [comment] 2016-03-09 00:04
https://trac.ffmpeg.org/wiki/Concatenate

**Comment by clagiordano** [comment] 2016-03-09 20:54
Thank you for your answer, I know that method and I have used it with php shell exec functions.
I hope it is implemented as a new feature in the future.

**Comment by clagiordano** [comment] 2016-03-09 21:05
Best (and fast) way indeed is use concat demuxer but video parts must be much as possible similar in video format, audio frequency, and obviously codec otherwise the demuxer generate artefacts or unpredictable results.
A useful trick is, as shown by documentation, a conversion to mpeg transport streams, only the container will be changed not the streams but simplifies final concat operation.
I used this method in production system and works well.
I hope it can be useful.

**Comment by patkar** [comment] 2016-03-09 21:17
Thanks for the info :+1:

**Comment by patkar** [comment] 2016-03-09 21:26
Duplicate of #69

**Closed by patkar** 2016-03-09 21:26 UTC
Labels: duplicate
